<?php return array (
		'database' => array(
			'driver' => 'mysql',
			'hostname' => 'localhost',
			'dbname' => 'srulscbq_cms',
			'user' => 'srulscbq_cms',
			'password' => '123abc',
		),
		'site' => array(
			'title' => 'Periódico Online | Tarma.com',
			'description' => 'hola soy el titulo del sitio',
			'webmaster_email' => 'pepeasdasd@gmail.com',
			'webmaster_name' => 'admin',
			'language' => 'es',
		),
		'key' => '75a1199e125ac787f689127537470c57',
		'path' => array(
			'includes' => 'includes',
			'models' => 'models',
			'controllers' => 'controllers',
			'views' => 'themes',
			'assets' => 'assets',
			'cache' => 'storage/cache',
			'logs' => 'storage/logs',
		),
		'theme' => 'default',
		'homepage_posts' => 5,
		'author_requires_posts' => true,
		'cache' => array(
			'expires' => 3,
		),
		'aliases' => array(
			'DB' => 'EC\\Database\\DB',
			'DBObject' => 'EC\\Database\\DBObject',
			'Query' => 'EC\\Database\\Query',
			'Url' => 'EC\\HTTP\\Url',
			'Redirect' => 'EC\\HTTP\\Redirect',
			'Response' => 'EC\\HTTP\\Response',
			'Header' => 'EC\\HTTP\\Header',
			'Param' => 'EC\\HTTP\\Param',
			'Log' => 'EC\\Storage\\Log',
			'Cache' => 'EC\\Storage\\Cache',
			'Cookie' => 'EC\\Storage\\Cookie',
			'App' => 'EC\\App',
			'Config' => 'EC\\Config',
			'Asset' => 'EC\\Asset',
			'Event' => 'EC\\Event',
			'File' => 'EC\\File',
			'Image' => 'EC\\Image',
			'View' => 'EC\\View',
			'Autoloader' => 'EC\\Autoloader',
			'Hash' => 'EC\\Auth\\Hash',
		),
		'feeds' => array(
			'fullpost' => true,
		),
		'available_languages' => array(
			'es' => 'Español (España)',
		),
	);